spring:
  redis:
    host: *****
    password: ****
    port: 6379
    jedis:
      pool:
        max-active: 10
        #hot fox
        #master
        #master
        #master
        #hot fox
        #hot fox
        #pull text
